# Generated by Django 4.1.5 on 2023-01-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="EnrollmentApplication",),
        migrations.DeleteModel(name="TechsyiqTeam",),
    ]
